export const store = [
  {
    id: 1,
    title: "360 Perforated Faux Leather Plump Shoe",
    img: "images/product-1.jpg",
    price: 5299,
    size: "5, 6, 7, 8, 9",
    seller: "Perfect Store",
    info:
      "Stand out from the crowd in this amazing and attractive high quality shoe. It is made with the buyer's comfort and elegance in mind. This is the shoe to go for whenever u are thinking of getting that perfect finishing touch for your outfit. It comes in different sizes. It is designed for comfort and uniqueness. Your cabinet would not be complete without this particular shoe in it. It is very durable and also highly affordable for both low income and high income earners. It speaks simplicity and uniqueness combined.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Casual Sneakers Ladies - White",
    img: "images/product-2.jpg",
    price: 11000,
    size: "5, 6, 7",
    seller: "Dovey",
    info:
      "These Fashion Trainers is crafted with a textured paneled design with perforated detail to promote a more breathable feel when wearing. A cushioned ankle collar is teamed with a cushioned insole to promote a comfortable fit. Situated on the forefoot is a full-length lace up fastening to ensure feet are locked in position to give you support at all times. Excellent coloring and branding complete the look.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Borets Safety Shoe - Black",
    img: "images/product-3.jpg",
    price: 10000,
    size: 10,
    seller: "Borets Resources Limited",
    info:
      "Borets safety shoe has been a market leader in the industry through its quality maintenance. Very strong that it can sustain the pressure of different whether. It can easily be adjusted to fit the user. Has high durability standard, very easy to wear, not heavy on the foot, available in different sizes, has well coupled rope and pendants for adjustment.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Carvela Chrissy Sneakers",
    img: "images/product-4.jpg",
    price: 19850,
    size: 7,
    seller: "House of Glitz",
    info:
      "Reminiscent of a starlit sky, the Chrissy trainers bring glamour to even the most low-key of looks. A classic athletic silhouette, the knitted upper is elasticated for a snug fit, trimmed with tonal panels at the edges and sat upon a boldly contrasting sole – you’ll be pleased to know that  has also managed to add an extra-padded sock for day-long cushioning and comfort",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Office Flat Plum - Light Brown",
    img: "images/product-5.jpg",
    price: 5299,
    size: "5, 6, 7, 8, 9",
    seller: "Perfect Store",
    info:
      "Stand out from the crowd in this amazing and attractive high quality shoe. It is made with the buyer's comfort and elegance in mind. This is the shoe to go for whenever u are thinking of getting that perfect finishing touch for your outfit. It comes in different sizes. It is designed for comfort and uniqueness. Your cabinet would not be complete without this particular shoe in it. It is very durable and also highly affordable for both low income and high income earners. It speaks simplicity and uniqueness combined.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Ladies Court Shoe - Black",
    img: "images/product-6.jpg",
    price: 20500,
    size: "8.5, 9.5, 10",
    seller: "House of Glitz",
    info:
      "Black Snake Print Court Shoes: Polish and gloss for all your favourite work-to-weekend looks, Flagship 75 by Nine West is a quintessentially elegant court shoe with a pointed toe, wearable 75mm heel and black upper with a high-shine finish.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Sleek Mesh Sneakers - Red And Blue",
    img: "images/product-7.jpg",
    price: 8500,
    size: "7, 8, 9, 10, 11, 12",
    seller: "Elements of Harmony",
    info:
      "Classic, refined, and modern, the upper fabric allows for breathability and the flat solid heels enable easy traction. The minimalist design means its perfect for the boardroom or after work at the bar. This is a step ahead of most brands, as her products provides comfort and durability to the everyone.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "String Bow Transparent Women Flat Shoe - Blue",
    img: "images/product-8.jpg",
    price: 5299,
    size: "5, 6, 7, 8, 9",
    seller: "Perfect Store",
    info:
      "Stand out from the crowd in this amazing and attractive high quality shoe. It is made with the buyer's comfort and elegance in mind. This is the shoe to go for whenever u are thinking of getting that perfect finishing touch for your outfit. It is designed for comfort and uniqueness. Your cabinet would not be complete without this particular shoe in it. Get this shoe today and you will be forever thankful you did. It is very durable and also highly affordable for both low income and high income earners. It speaks simplicity and uniqueness combined.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Fashion Forms Genuine Leather Suede Shoe For Real Men",
    img: "images/product-9.jpg",
    price: 14000,
    size: "13, 14, 15",
    seller: "Konga",
    info:
      "Nothing beats the timeless appeal of our shoes, offering a distinct look that gets you attention. Jazz up your outfits and add sophistication to your look with this exquisite shoe that has been specially designed for that personality of class and style.Appearance is the best letter of recommendation. Spice up the attire with this elegant shoe made of finest and  quality material. The  attractive outlook of the shoe bring out the overall beauty in you. just rock and roll",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Ladies High Heels Stiletto Shoe - Red",
    img: "images/product-10.jpg",
    price: 9800,
    size: "6, 7, 8",
    seller: "Khopac",
    info:
      "High- quality sophisticated and glamorous double ankle strap court shoes for women, designed by the Lost Ink team in London.The stiletto heels and ankle strap allows this style of heels to be worn all day long.Beautiful and classy lady's shoes, now it’s easy to buy shoes online.We all need a good red ankle strap court shoes that go with any outfit.This pump's shoes itself are attractive yet comfortable to wear and the padded internal shoe sole makes everything so much better for your feet.Perfect for work, gala events, outings, party, function, and occasions or just casual wear.Shoes comes with an extra heel cap.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Ankle Strap & Slingback Shoes",
    img: "images/product-11.jpg",
    price: 11000,
    size: 7,
    seller: "Kellyzolae-Shopping",
    info:
      'With their ankle design adornment, these sandals will really help you shine. upper 4" heel leather block sole CALL IT SPRING IS AN ALDO GROUP BRAND.Elegant simplicity, versatility with affordability for a well put together look always; these slippers are easy to wear letting you spend less to look great.Update your collection and step out in style with these classy',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Men's Ankle Corporate Shoe",
    img: "images/product-12.jpg",
    price: 14500,
    size: "7, 8, 9, 10, 11, 12",
    seller: "Elements of Harmony",
    info:
      "Crafted with a premium suede upper and featuring lace-up design and solid outsoles that stand the test of time, keep your cool and update your footwear collection with this classic, versatile design. Armstrong is a durable and unique brand, it serves its purpose and even more.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 10,
  title: "Ladies High Heels Stiletto Shoe",
  img: "images/product-10.jpg",
  price: 9800,
  size: "6, 7, 8",
  seller: "Khopac",
  info:
    "High- quality sophisticated and glamorous double ankle strap court shoes for women, designed by the Lost Ink team in London.The stiletto heels and ankle strap allows this style of heels to be worn all day long.Beautiful and classy lady's shoes, now it’s easy to buy shoes online.We all need a good red ankle strap court shoes that go with any outfit.This pump's shoes itself are attractive yet comfortable to wear and the padded internal shoe sole makes everything so much better for your feet.Perfect for work, gala events, outings, party, function, and occasions or just casual wear.Shoes comes with an extra heel cap.",
  inCart: false,
  count: 0,
  total: 0,
};
